- name: Add repos (persistent)
  command: helm repo add {{ item.name }} {{ item.url }}
  loop:
    - { name: "jenkins", url: "https://charts.jenkins.io" }
    - { name: "argo", url: "https://argoproj.github.io/argo-helm" }

- name: Install Jenkins with Helm using gp2 storage
  kubernetes.core.helm:
    name: jenkins
    chart_ref: jenkins/jenkins
    release_namespace: jenkins
    create_namespace: true
    state: present
    kubeconfig: "/home/{{ ansible_user }}/.kube/config"
    values:
      controller:
        jenkinsHome: "/var/jenkins_home"
      persistence:
        enabled: true
        storageClass: "gp2"

- name: Ensure pip3 is installed on bastion
  ansible.builtin.package:
    name: python3-pip
    state: present

- name: Install kubernetes Python module via pip3 on bastion
  ansible.builtin.pip:
    name: kubernetes
    executable: pip3

- name: Add Kaniko Service Account
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: kaniko-sa
        namespace: jenkins
        annotations:
          eks.amazonaws.com/role-arn: arn:aws:iam::991424600343:role/eks-kaniko-role
    kubeconfig: "/home/{{ ansible_user }}/.kube/config"


- name: Install ArgoCD with Helm
  kubernetes.core.helm:
    name: argocd
    chart_ref: argo/argo-cd
    release_namespace: argocd
    create_namespace: true
    state: present
    kubeconfig: "/home/{{ ansible_user }}/.kube/config"

